[book]
authors = ["Kennan Hunter"]
language = "en"
multilingual = false
src = "book"
title = "Kennan's Photo Server"

[build]
build-dir = "./target/book"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
cname = "photo.kennan.tech"
