on: [push]

name: Build and Test Binary

jobs:
  check:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install lastest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Check for formating
        uses: actions-rs/cargo@v1
        with:
          command: fmt

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy -- -D warnings

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test --release

      - name: Build Binary
        uses: actions-rs/cargo@v1
        with:
          command: build --release

      - name: Expose Binary as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: photo-binary
          path: target/release/photo

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/photo
